{"status": "broken", "attachments": [{"source": "8d1ccb79-08be-40a3-ae2b-9b0c51bd39fa-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "26417f5f-3d98-44b9-9031-173d43ccaf53-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "b8dfcdb4-79e9-40cc-8e25-4ac414f2293a-attachment.txt", "type": "text/plain", "name": "stderr"}], "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "experiment_test"}, {"name": "subSuite", "value": "TestComplexScenario"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "25925-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.experiment_test"}], "stop": 1608301139141, "uuid": "95557638-3128-40e6-b727-19400adfe7ff", "historyId": "8c01b8dc4b44542c0952bde08d641ae2", "start": 1608301139140, "fullName": "tests.experiment_test.TestComplexScenario#test_movement", "statusDetails": {"message": "NameError: global name 'omni_base' is not defined", "trace": "self = <tests.experiment_test.TestComplexScenario instance at 0x7f2dead44b00>\n\n    def test_movement(self):\n>       omni_base.go_abs(0, 1.0, 0.0, 300.0)\nE       NameError: global name 'omni_base' is not defined\n\ntests/experiment_test.py:71: NameError"}, "name": "test_movement"}