[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:34717/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:44149/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:42445/], count 2
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf_static] adding connection to [http://192.168.0.101:37215/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:40569/], count 2
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:38135/], count 4
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:37215/], count 5
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:44519/], count 5
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:40407/], count 5
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:33117/], count 5
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:35509/], count 6
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] adding connection to [http://192.168.0.101:41977/], count 10
[32mINFO    [0m rospy.internal:core.py:138 topic[/move_base/move/feedback] adding connection to [http://192.168.0.101:44467/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/move_base/move/result] adding connection to [http://192.168.0.101:44467/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/move_base/move/status] adding connection to [http://192.168.0.101:44467/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/rosout] adding connection to [/rosout], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/move_base/move/cancel] adding connection to [/move_base], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/move_base/move/goal] adding connection to [/move_base], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/feedback] adding connection to [http://192.168.0.101:41977/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/status] adding connection to [http://192.168.0.101:41977/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/result] adding connection to [http://192.168.0.101:41977/], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/goal] adding connection to [/gazebo], count 0
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/cancel] adding connection to [/gazebo], count 0
[32mINFO    [0m rospy.core:core.py:454 signal_shutdown [shutdown]
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/cancel] removing connection to /gazebo
[32mINFO    [0m rospy.internal:core.py:138 topic[/rosout] removing connection to /rosout
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/goal] removing connection to /gazebo
[32mINFO    [0m rospy.internal:core.py:138 topic[/move_base/move/goal] removing connection to /move_base
[32mINFO    [0m rospy.internal:core.py:138 topic[/move_base/move/cancel] removing connection to /move_base
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/result] removing connection to http://192.168.0.101:41977/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:40439 (http://192.168.0.101:41977/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 651, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[1m[31mERROR   [0m rospy.topics:topics.py:329 Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 839, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:51287 (http://192.168.0.101:44467/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[32mINFO    [0m rospy.internal:core.py:138 topic[/move_base/move/feedback] removing connection to http://192.168.0.101:44467/
[32mINFO    [0m rospy.internal:core.py:138 topic[/move_base/move/status] removing connection to http://192.168.0.101:44467/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/feedback] removing connection to http://192.168.0.101:41977/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:40439 (http://192.168.0.101:41977/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 651, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[1m[31mERROR   [0m rospy.topics:topics.py:329 Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 839, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:34717/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:44149/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:42445/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:53365 (http://192.168.0.101:42445/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:40569/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:38135/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:41731 (http://192.168.0.101:38135/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:37215/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:44519/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:40407/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:33117/
[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:35509/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:47669 (http://192.168.0.101:35509/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 559, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[32mINFO    [0m rospy.internal:core.py:138 topic[/tf] removing connection to http://192.168.0.101:41977/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:40439 (http://192.168.0.101:41977/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 651, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[32mINFO    [0m rospy.internal:core.py:138 topic[/tf_static] removing connection to http://192.168.0.101:37215/
[33mWARNING [0m rospy.internal:core.py:144 Unknown error initiating TCP/IP socket to 192.168.0.101:34871 (http://192.168.0.101:37215/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 651, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[1m[31mERROR   [0m rospy.topics:topics.py:329 Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 839, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[32mINFO    [0m rospy.internal:core.py:138 topic[/clock] removing connection to http://192.168.0.101:41977/
[32mINFO    [0m rospy.internal:core.py:138 topic[/move_base/move/result] removing connection to http://192.168.0.101:44467/
[32mINFO    [0m rospy.internal:core.py:138 topic[/hsrb/omni_base_controller/follow_joint_trajectory/status] removing connection to http://192.168.0.101:41977/
[32mINFO    [0m rospy.impl.masterslave:masterslave.py:342 shutdown