{"status": "broken", "description": "Defines a scenario for the rest of the tests to run in using coodrinates.\n        ", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "complex_test"}, {"name": "subSuite", "value": "TestComplexScenario"}, {"name": "host", "value": "Hyper-Dock"}, {"name": "thread", "value": "3266-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "tests.complex_test"}], "stop": 1608279050871, "uuid": "6e65d8ec-6be7-4320-9fd3-b2aa58d327d7", "historyId": "abb855563adc9008a9436da38b1dfb41", "name": "test_verification_of_navigation", "start": 1608279050871, "fullName": "tests.complex_test.TestComplexScenario#test_verification_of_navigation", "statusDetails": {"message": "NameError: global name 'destination_coord' is not defined", "trace": "self = <tests.complex_test.TestComplexScenario instance at 0x7fa9abcfacf8>\n\n    def test_verification_of_navigation(self):\n        \"\"\"Defines a scenario for the rest of the tests to run in using coodrinates.\n        \"\"\"\n        coord_x, coord_y, direction = 0.210, 2.683, 90\n>       destination_coord.append(coord_x)\nE       NameError: global name 'destination_coord' is not defined\n\ntests/complex_test.py:70: NameError"}, "attachments": [{"source": "548e4627-3740-4ce2-9079-1bed26f2741f-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "6398d49a-51f9-4d7b-98b4-10036bb6988c-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "f74c3824-2bd8-428b-b7fd-fdb7de72324f-attachment.txt", "type": "text/plain", "name": "stderr"}]}